export const FETCHING = "_FETCHING"
export const PENDING = "_PENDING"
export const FULLFILLED = "_FULFILLED"
export const REJECTED = "_REJECTED"

export const authLogin = "AUTH_LOGIN"
export const getAllProductsWithPagination = "GET_ALLPRODUCTS"
export const orderByNewItem = "GET_PRODUCT_BY_NEW_ITEM"
export const nextPagination = "GET_PRODUCT_PAGINATION"

export const idProduct = "SET_ID_PRODUCT"
export const sizeProduct = "SET_SIZE"
export const deliveryProduct = "SET_DELIVERY"
export const timeProduct = "SET_TIME"
export const countInc = "COUNT_INCREMENT"
export const countDec = "COUNT_DECREMENT"
export const imgProduct = "SET_IMAGE"
export const nameProduct = "SET_NAME"
export const priceProduct = "SET_PRICE"
export const checkOutProduct = "GET_CHECKOUT"